openapi: "3.0.0"
info:
  version: "2.0.0"
  title: Click and Take off - Flight Segment Fetch and Assignment API
servers:
  - url: "https://dev.clickandtakeoff.com/api"
  - url: "https://my.clickandtakeoff.com/api"
security:
  - bearerAuth: []
paths:
  "/cto/flight/segment":
    get:
      summary: Fetch a list of flights segments
      tags:
        - "Flight Segment"
      description: It returns a list of flights segments the user has access to
      parameters:
        - name: device
          in: query
          description: "F-XXXX"
          required: true
          schema:
            type: string
        - name: club
          in: query
          description: "Click and Take Off"
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: "in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: "in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          required: true
          schema:
            type: string
            format: date-time
        - name: nonAssigned
          in: query
          description: "false"
          required: false
          schema:
            type: boolean
        - name: assigned
          in: query
          description: "false"
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlightSegmentCtoItems"
        "400":
          description: ERROR
        "401":
          description: Unauthorized / Token not valid for this club
        "402":
          description: CTO server is not available. Please try later
        "404":
          description: Club not found / Device not found

    put:
      summary:  🚧🚧🚧🚧🚧 - Flight Segment Assignment
      tags:
        - "Flight Segment"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                device:
                  type: string
                  description: "F-XXXX"
                club:
                  type: string
                  description: "Click and Take off"
                pilotEmail:
                  type: string
                  description: "test@test.cto"
                instructorEmail:
                  type: string
                  description: "test@test.cto"
                pilotId:
                  type: integer
                  description: "0"
                instructorId:
                  type: integer
                  description: "0"
                from:
                  type: string
                  description: "in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
                  format: date-time
                to:
                  type: string
                  description: "in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
                  format: date-time
      responses:
        "200":
          description: Flight Segment has been assigned correctly
        "401":
          description: Unauthorized
        "400":
          description: ERROR / Pilot not indicated / 
        "402":
          description: CTO server is not available. Please try later
        "404":
          description: Club not found / Device not found / Instructor not found 
        "406":
          description: Pilot not found
        "409":
          description: Conflict / Choose a pilot in the indicated club

components:
  schemas:
    FlightSegmentCtoItems:
      type: object
      properties:
        clubName:
          type: string
        deviceName:
          type: string
        startTime:
          description: "Engine start time, in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          type: string
          format: date-time
        endTime:
          description: "Engine end time, in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          type: string
          format: date-time
        startTimeFlight:
          description: "Movement start time, in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          type: string
          format: date-time
        endTimeFlight:
          description: "Movement end time, in ISO 8601 format. eg. `1963-11-22T18:30:00Z`"
          type: string
          format: date-time
        icaoAeroStart:
          type: string
          description: "Starting aerodrome"
        icaoAeroEnd:
          type: string
          description: "Arrival aerodrome"
        hourMeterStart:
          type: integer
          description: "Engine start hour meter"
        hourMeterStartFlight:
          type: integer
          description: "Movement start hour meter"
        hourMeterEnd:
          type: integer
          description: "Engine stop hour meter"
        hourMeterEndFlight:
          type: integer
          description: "Movement stop hour meter"
        pilotEmail:
          type: string
          description: "Pilot email adress, empty if flight has not been assigned"
        instructorEmail:
          type: string
          description: "instructor email adress, empty if flight has not been assigned or has no instructor"
        landing:
          type: integer
          description: "Landing total number, 0 if none"

  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Token authorization for identify club in the case of externe call of api
      name: Authorization
      in: header
